# -*- coding: utf-8 -*-
import sys
import clr

# Import Revit API Elements
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

# Import Dynamo Document and Transaction Services
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import System for .NET Collections (HashSet Support)
clr.AddReference('System')
import System

# 1. ACTIVE DOCUMENT INITIALIZATION
doc = DocumentManager.Instance.CurrentDBDocument

# Reporting counters for the final log output
groups_deleted = 0
views_deleted = 0
templates_deleted = 0
rvt_unloaded = 0
links_removed = 0
total_purged = 0

# =========================================================================
# BLOCK A: GROUPS, VIEWS, TEMPLATES, AND LINK MANAGEMENT
# Executed within a single continuous transaction block to optimize speed
# =========================================================================
TransactionManager.Instance.EnsureInTransaction(doc)

# --- STEP 1: PURGE MODEL & DETAIL GROUPS FROM THE PROJECT BROWSER ---
group_ids = FilteredElementCollector(doc).OfClass(GroupType).ToElementIds()
for g_id in group_ids:
    try:
        doc.Delete(g_id)
        groups_deleted += 1
    except: pass

# --- STEP 2: PURGE 3D VIEWS & VIEW TEMPLATES (Preserving 2D Sheets and Plans) ---
view_ids = FilteredElementCollector(doc).OfClass(View).ToElementIds()
for v_id in view_ids:
    try:
        view = doc.GetElement(v_id)
        if view is None or view.ViewType in [ViewType.Schedule, ViewType.Internal, ViewType.ProjectBrowser]:
            continue
            
        if view.IsTemplate:
            doc.Delete(v_id)
            templates_deleted += 1
            continue 

        if view.ViewType == ViewType.ThreeD:
            v_name = view.Name.upper()
            # Safety gate: Protect critical coordination and export views
            if "3D EMISSÃO" in v_name or "3D NAVIS" in v_name or "3D EMISSAO" in v_name:
                continue 
            doc.Delete(v_id)
            views_deleted += 1
    except: pass

# --- STEP 3: LINK DETACHMENT (Unload RVTs and Hard Delete Formats) ---
# Unload Revit Links to safely release server RAM memory
rvt_links = FilteredElementCollector(doc).OfClass(RevitLinkType).ToElements()
for link in rvt_links:
    if not link.IsNestedLink:
        try:
            if link.GetLinkedFileStatus() == LinkedFileStatus.Loaded:
                link.Unload(None)
                rvt_unloaded += 1
        except: pass

# Dynamic safety array of alternative link classes for complete structural removal
link_classes = [CADLinkType, PointCloudType]

# Fallback injection to maintain compatibility across older Revit API installations
try: link_classes.append(CoordinationModelType)
except: pass
try: link_classes.append(TopographyLinkType)
except: pass

for cls in link_classes:
    try:
        lnk_ids = FilteredElementCollector(doc).OfClass(cls).ToElementIds()
        for l_id in lnk_ids:
            try:
                doc.Delete(l_id)
                links_removed += 1
            except: pass
    except: pass

# Commit Block A transactions to update the BIM model state before compiling the Purge list
TransactionManager.Instance.TransactionTaskDone()


# =========================================================================
# BLOCK B: RECURSIVE DEEP PURGE OF UNUSED ELEMENTS (Cascading Garbage Collection)
# Executes inside repeated cycles to clean deep family and material dependencies
# =========================================================================
loop_safety = 0
max_loops = 10 

while loop_safety < max_loops:
    TransactionManager.Instance.EnsureInTransaction(doc)
    
    # Compile the orphan elements list generated by Block A modifications using native .NET HashSet
    try:
        unused_ids = doc.GetUnusedElements(System.Collections.Generic.HashSet[ElementId]())
    except:
        TransactionManager.Instance.TransactionTaskDone()
        break
    
    if not unused_ids or unused_ids.Count == 0:
        TransactionManager.Instance.TransactionTaskDone()
        break 
        
    purged_this_loop = 0
    for e_id in unused_ids:
        try:
            doc.Delete(e_id)
            purged_this_loop += 1
            total_purged += 1
        except: pass
            
    TransactionManager.Instance.TransactionTaskDone()
    
    # If a cycle yields zero element cleanups, the database is optimized; break loop
    if purged_this_loop == 0:
        break
        
    loop_safety += 1

# =========================================================================
# FINAL BIM PERFORMANCE LOG REPORT
# =========================================================================
report_log = [
    "🔥 CLOUD DELIVERY MODEL OPTIMIZER EXECUTED SUCCESSFULLY! 🔥",
    "-"*50,
    "• Model & Detail Groups purged from Browser: {}".format(groups_deleted),
    "• View Templates destroyed: {}".format(templates_deleted),
    "• Redundant 3D Views deleted (Saved EMISSÃO & NAVIS): {}".format(views_deleted),
    "• Revit Cloud Links safely unloaded: {}".format(rvt_unloaded),
    "• Hard links completely removed (DWG, Clouds, NWD, Topo): {}".format(links_removed),
    "• Secondary cascading elements purged (Deep Purge): {}".format(total_purged),
    "• Optimization recursive cycles required: {}".format(loop_safety),
    "-"*50,
    "Model performance is 100% optimized and ready for cloud upload/emission!"
]

OUT = "\n".join(report_log)
